### PR TITLE
Aux fixes

### LINKED ISSUE #216: Auxservice, NullPointerException
In runs 
20140405_130
20140627_016
```
Exception in thread "Thread-1" java.lang.RuntimeException: Process stopped after exception: java.lang.NullPointerException
        at stream.runtime.ProcessThread.run(ProcessThread.java:170)
Caused by: java.lang.NullPointerException
        at fact.auxservice.AuxFileService.readDataFromFile(AuxFileService.java:92)
        at fact.auxservice.AuxFileService.getAuxiliaryData(AuxFileService.java:66)
        at fact.features.source.SourcePosition.process(SourcePosition.java:212)
        at stream.runtime.AbstractProcess.process(AbstractProcess.java:126)
        at stream.runtime.AbstractProcess.execute(AbstractProcess.java:184)
        at stream.runtime.ProcessThread.run(ProcessThread.java:129)
```

### PR DESCRIPTION
**Pull request by mackaiver**
Hello. 
Since the other two pull requests  #200 and #165 are somehow completely f#d up I just redid it here. Maybe this also fixes #216

### CODE REVIEW

File: src/main/java/fact/auxservice/AuxCache.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
+package fact.auxservice;
+
+
+import org.joda.time.DateTime;
```
Comment (MaxNoe) [inline src/main/java/fact/auxservice/AuxCache.java]: jodatime

File: src/main/java/fact/auxservice/AuxFileService.java [hunk 2]
```diff
@@ -53,123 +78,96 @@
...
+            throw new IOException("No auxpoint found for the given timestamp " + eventTimeStamp);
+        }
     }
 
 
     /**
-     * Reads data from a file provided by the url and creates an AuxPoint for each event in the file.
-     * @param auxFileUrl url to the auxfile
-     * @return treeset containing auxpoints ordered by their timestamp
+     * This method returns an AuxPoints for a whole night according to the strategy and the time stamp passed to this method.
```
Comment (MaxNoe) [inline src/main/java/fact/auxservice/AuxFileService.java]: Grammar

File: src/main/java/fact/auxservice/AuxPoint.java [hunk 3]
```diff
@@ -59,8 +60,20 @@ public Double getDouble(String key){
     }
 
     /**
+     * Returns the value for the key iff it exists and its a Double. Returns null otherwise.
```
Comment (MaxNoe) [inline src/main/java/fact/auxservice/AuxPoint.java]: its a Float?

File: src/main/java/fact/auxservice/AuxPoint.java [hunk 4]
```diff
@@ -47,7 +47,8 @@ public ZonedDateTime getTimeStamp() {
 
     /**
      * Returns the value for the key iff it exists and its a Double. Returns null otherwise.
-     * @param key
+     *
+     * @param key the name of the aux data you want to access. e.g. the name of the column in the aux fits file
      * @return the value or null
      */
     public Double getDouble(String key){
```
Comment (MaxNoe) [inline src/main/java/fact/auxservice/AuxPoint.java]: Do we want to use Optionals here instead of returning null?

File: src/main/java/fact/auxservice/AuxPoint.java [hunk 5]
```diff
@@ -124,6 +125,24 @@ public String getString(String key){
     }
 
 
+    /**
+     * Returns an Optional containing the value with the given class iff it exists. Otherwise its empty.
```
Comment (MaxNoe) [inline src/main/java/fact/auxservice/AuxPoint.java]: ifffffff

File: src/main/java/fact/auxservice/AuxPoint.java [hunk 6]
```diff
@@ -106,6 +125,24 @@ public String getString(String key){
...
+     * @param key the name of the aux data you want to access. e.g. the name of the column in the aux fits file
+     * @param cls the data type you expect the value to be in
+     * @return an optional containing the value or an empty optional.
+     */
+    public <T> Optional<T> getValue(String key, Class<T> cls){
```
Comment (MaxNoe) [inline src/main/java/fact/auxservice/AuxPoint.java]: This is beauty
