### PR TITLE
Empty drs file, fixes #353, fixes #351

### LINKED ISSUE #351: Make calibration.xml work with FactFileMultistream
Currently the `DrsCalibration` in the `calibration.xml` uses the `url="${drsfile}"` method of getting the drs file, which makes the xml incompatible with the use of `FactFileMultistream`. I think it would be nice if it would work with it, as it means one can just reuse it.

There are two options I can think of to make this work:

* remove the `ulr=${drsfile}` and have a processor that injects the `${drsfile}` into the datastream as the `@drsFile` item.
* by default or by parameter, make it that the `DrsCalibration`-Processor switches to the `@drsFile` option if the given url can't be read (For example because the string is empty or because it couldn't be read).

### LINKED ISSUE #353: std analysis erna observations does not work anymore with erna.process_fact_data
Using the recent fact-tools version with erna.process_fact_data does not work anymore for two reasons:

1. it still uses the old `fact.auxservice.SqliteService`, which is not needed anymore since there is `fact.auxservice.AuxFileService` that can handle directory trees.

https://github.com/fact-project/fact-tools/blob/328feab9e6b9136057e410a8227395a206298b6e/examples/forErna/std_analysis_erna_observations.xml#L8-L12

2. erna provides the drs-file as key-value-pair in the data item via `fact.io.FactFileListMultiStream` but `classpath:/analysis/calibration.xml` uses `fact.datacorrection.DrsCalibration` with a URL given by a property `"${drsfile}"` this way the key `@drsFile`is never checked. 

https://github.com/fact-project/fact-tools/blob/328feab9e6b9136057e410a8227395a206298b6e/src/main/resources/analysis/calibration.xml#L11-L15

I suggest:

1. exchange `fact.auxservice.SqliteService` by `fact.auxservice.AuxFileService`
2. delete: https://github.com/fact-project/fact-tools/blob/328feab9e6b9136057e410a8227395a206298b6e/src/main/resources/analysis/calibration.xml#L12
and put a `<stream.data.SetValue key="@drsFile" value "${drsfile}"/>` into the std-analysis.

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by jebuss** [comment]
fixes #353

**Comment by jebuss** [comment]
fixes #351

**Comment by MaxNoe** [comment]
Yes, the idea was to set it to the empty string!

**Comment by MaxNoe** [comment]
It has to be set, but now the empty string is a valid value.

**Comment by jebuss** [comment]
Make sense to me, but even with en empty property ` <property name="drsfile" value="" />`  I still get:

```
$ java -jar target/fact-tools-v1.0.2-12-g0bd380a-dirty.jar examples/forErna/std_analysis_erna_observations.xml
streams exited on error: Error while creating instance of 'fact.datacorrection.DrsCalibration'
java.lang.IllegalArgumentException: Error while creating instance of 'fact.datacorrection.DrsCalibration'
	at stream.runtime.setup.factory.DefaultProcessFactory.createProcessorAndRegisterServices(DefaultProcessFactory.java:295)
	at stream.runtime.setup.factory.DefaultProcessFactory.createNestedProcessors(DefaultProcessFactory.java:277)
	at stream.runtime.setup.factory.DefaultProcessFactory.createAndRegisterProcesses(DefaultProcessFactory.java:255)
	at stream.runtime.setup.handler.ProcessElementHandler.handleElement(ProcessElementHandler.java:96)
	at stream.runtime.ProcessContainer.init(ProcessContainer.java:517)
	at stream.runtime.ProcessContainer.<init>(ProcessContainer.java:401)
	at stream.runtime.ProcessContainer.<init>(ProcessContainer.java:250)
	at stream.run.main(run.java:164)
	at stream.run.main(run.java:147)
	at fact.run.main(run.java:26)
Caused by: java.lang.IllegalArgumentException: Property drsfile is not set.
	at stream.util.Variables.substitute(Variables.java:157)
	at stream.util.Variables.substitute(Variables.java:121)
	at stream.util.Variables.expand(Variables.java:113)
	at stream.runtime.setup.factory.ObjectFactory.create(ObjectFactory.java:243)
	at stream.runtime.setup.factory.ObjectFactory.create(ObjectFactory.java:214)
	at stream.runtime.setup.factory.DefaultProcessFactory.createProcessorAndRegisterServices(DefaultProcessFactory.java:293)
```

Dunno why that is

File: src/main/java/fact/datacorrection/DrsCalibration.java [hunk 1]
```diff
@@ -267,11 +269,20 @@ public Data process(Data data) {
 
     @Override
     public void init(ProcessContext processContext) throws Exception {
-        if (url != null) {
+
+        if (!url.isEmpty()) {
```
Comment (jebuss) [inline src/main/java/fact/datacorrection/DrsCalibration.java]: it seems that in case the property is empty this line is never reached. I assume that streams does not handle empty properties very well.

Comment (jebuss) [reply src/main/java/fact/datacorrection/DrsCalibration.java]: However, searching for a specific sting works `if (!url.equals("a"))` and in the XML `<property name="drsfile" value="a" />`.

**Comment by MaxNoe** [comment]
I opened a PR in streams to enable setting empty properties here: https://bitbucket.org/cbockermann/streams/pull-requests/15/allow-empty-properties

**Comment by MaxNoe** [comment]
Just waiting for the tests to pass
